6 задание
anisimovdenis90/Java_Level_2_HomeWorks pull request #6
Opened 2020-03-16 14:02 UTC by anisimovdenis90

Не успел до конца разобраться с домашним заданием №6. При подключении клиента выскакивает EOFException . Я так понимаю какая-то проблема с BufferedReader` ом при чтении с консоли...

2020-03-17 13:01 UTC, anisimovdenis90 commented
Переделал 6 практическое задание. Добавил возможность подключения нескольких клиентов. Есть баг: при подключении каждого последующего клиента, сервер не читает сообщения от предыдущего, но сам отправляет сообщения всем.
К сожалению сейчас у меня совсем мало свободного времени, не успеваю до конца разобраться...

2020-03-20 19:41 UTC, OKrylov requested changes
В целом все отлично, но есть пара замечаний

2020-03-20 19:41 UTC, OKrylov commented on src/HomeWork6/Client.java
> +                        break;
делать break после exit не имеет смысла

2020-03-20 19:41 UTC, OKrylov commented on src/HomeWork6/Server.java
> +                runSendMessage();
не нужно создавать поток на отправку сообщений на каждое подключение, надо вынести из цикла

2020-03-20 19:41 UTC, OKrylov commented on src/HomeWork6/Server.java
> +                runInputThread();
создаем данный поток на каждое отдельное подключение, передавая туда сокет

2020-03-20 19:41 UTC, OKrylov commented on src/HomeWork6/Server.java
> +        for (Socket connection : connections) {
уходим от цикла, передаем сокет как параметр

2020-03-20 19:41 UTC, OKrylov commented on src/HomeWork6/Server.java
> +                        System.out.println("Соединение завершено");
при отсоединение удаляем из списка соединений

2020-03-22 12:20 UTC, merged